railstutorial: "https://www.railstutorial.org/"
book: "https://www.railstutorial.org/book"
screencast_series: "http://screencasts.railstutorial.org/"
RubyonRails: "http://rubyonrails.org/"
RailsTutorialhelp: "https://www.railstutorial.org/help"
RailsAuthor: "https://www.michaelhartl.com/"
RailsContact: "https://www.railstutorial.org/contact"
